Repository kornicameister/loguru-mypy, pull requests merged in 2020-11, with the labels that each got.

#43 Leverage mypy to check str.format expressions
  loguru_mypy/__init__.py
  typesafety/test_builtin_severities.yml
  typesafety/test_dot_access.yml
Labels: size/L

#59 Test against several versions of mypy & loguru
  .github/workflows/ci.yml
  requirements/tests.txt
Labels: size/S

#60 Pin mypy version on lower boundary
  loguru_mypy/__init__.py
Labels: size/XS

#61 Add mypy compatibility note
  README.md
Labels: size/XS

#63 Be specific when tox runs
  .github/workflows/ci.yml
Labels: size/S

#64 Setup requirements for automerge
  .github/workflows/ci.yml
  requirements.txt
  requirements/dev/base.txt
  requirements/dev/flake8.txt
  requirements/dev/mypy.txt
  requirements/dev/tests.txt
  requirements/dev/yapf.txt
  requirements/prod/requires.txt
  test-requirements.txt
  tox.ini
Labels: automerge

#65 Add coverage calculation
  .github/workflows/ci.yml
  tox.ini
Labels: size/S
