Repository kornicameister/loguru-mypy, pull requests merged in 2021-01, with the labels that each got.

#79 Accept numbers (int,float) for loguru calls
  loguru_mypy/__init__.py
  typesafety/test_issue_49.yml
Labels: size/S

#80 Accept variables (NameExpr) in loguru calls
  loguru_mypy/__init__.py
  typesafety/test_issue_49.yml
Labels: size/M

#81 Accept Any Single Argument
  loguru_mypy/__init__.py
  typesafety/test_issue_49.yml
Labels: size/M

#86 Add mypy==0.800
  .github/workflows/ci.yml
  README.md
Labels: size/XS

#87 Bump pytest to 6.2.2
  requirements/dev/tests.txt
Labels: size/XS

#88 [refactor] Pull out arguments unpacking to function
  loguru_mypy/__init__.py
Labels: size/M
